Repository kimxogus/react-native-version-check, pull requests merged in 2019-05, with the labels that each got.

#67 Change PlayStore crawler hardcoded string to regex
  packages/react-native-version-check/src/providers/__tests__/playStore.js
  packages/react-native-version-check/src/providers/playStore.js
Labels: size/S

#83 update dependencies
  lerna.json
  package-lock.json
  package.json
  packages/react-native-version-check-expo/.npmignore
  packages/react-native-version-check-expo/package-lock.json
  packages/react-native-version-check-expo/package.json
  packages/react-native-version-check/.npmignore
  packages/react-native-version-check/package-lock.json
  packages/react-native-version-check/package.json
Labels: security fix

#86 remove files field in package.json
  package-lock.json
  packages/react-native-version-check-expo/package.json
  packages/react-native-version-check/package.json
Labels: bugfix, size/S
